spring:
  application:
    name: review-service
server:
  port: 7003
  error:
    include-message: always
logging:
  level:
    root: INFO
    taz.amin: DEBUG

---
spring.config.activate.on-profile: docker
server.port: 8080